title: Deep Forest
repo: https://github.com/ian-pvd/deep-forest
license: https://github.com/ian-pvd/deep-forest/blob/main/LICENSE.txt
author:
  name: ian-pvd
  email: pvdindustrial@gmail.com
twitter: deep_forest

# Jekyll plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "home"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"

# Theme config
theme_color: dark-green # possible values: dark-green light-green dark-red light-red, default: dark-green
reduce_motion: false # possible values: true false, default: false
show_excerpts: false # possible values: true false, default: false
logo_url: '/assets/images/logo.svg' # logo url, default: /assets/logo.svg
avatar_url: '/assets/images/avatar.png' # avatar url, default: /assets/avatar.png

# Theme settings

description: >
  Jekyll portfolio theme for developers
about: >
  Deep Forest is a theme for developer portfolios hosted on github pages. Add examples of your work, blog posts, or a resume.

# To enable Google Analytics, add your tracking ID here.
# google_analytics: UA-NNNNNNNN-N

# Add pages to the site-header primary navigation in this order.
primary_nav:
  - resume.md
  - portfolio.md
  - posts.md
  - about.md

# Add pages to the site-footer utilities navigation in this order.
utilities_nav:
  - resume.md
  - portfolio.md
  - posts.md
  - contact.md
  - about.md

# Social media links
social_links:
#  - { platform: dribbble,      user_url: "https://dribbble.com/deep-forest" }
#  - { platform: facebook,      user_url: "https://www.facebook.com/deep-forest" }
#  - { platform: flickr,        user_url: "https://www.flickr.com/photos/deep-forest" }
 - { platform: github,        user_url: "https://github.com/ian-pvd/deep-forest" }
#  - { platform: instagram,     user_url: "https://www.instagram.com/deep-forest" }
 - { platform: linkedin,      user_url: "https://www.linkedin.com/in/deep-forest" }
 - { platform: codepen,       user_url: "https://codepen.io/deep-forest" }
 - { platform: twitter,       user_url: "https://twitter.com/deep-forest" }
 - { platform: stackoverflow, user_url: "https://stackoverflow.com/users/1234567/deep-forest" }
#  - { platform: youtube,       user_url: "https://www.youtube.com/deep-forest" }

# Build settings

# SCSS config
sass:
  sass_dir: _sass
  style: nested # possible values: nested expanded compact compressed
