title: Deep Forest
repo: https://github.com/ian-pvd/deep-forest
author:
  name: ian-pvd
  email: pvdindustrial@gmail.com

# Jekyll plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme settings

description: >
  Jekyll portfolio theme for developers

# To enable Google Analytics, add your tracking ID here.
# google_analytics: UA-NNNNNNNN-N

# Add pages to the site-header primary navigation in this order.
primary_nav:
  - resume.md
  - portfolio.md
  - about.md

# Add pages to the site-footer utilities navigation in this order.
utilities_nav:
  - about.md
  - contact.md

theme_color: dark-green # possible values: dark-green light-green dark-red light-red, default: dark-green
reduce_motion: false # possible values: true false, default: false
show_excerpts: false # possible values: true false, default: false

# Social media links
social_links:
 - { platform: dribbble,      user_url: "https://dribbble.com/jekyll" }
 - { platform: facebook,      user_url: "https://www.facebook.com/jekyll" }
 - { platform: flickr,        user_url: "https://www.flickr.com/photos/jekyll" }
 - { platform: github,        user_url: "https://github.com/jekyll/minima" }
 - { platform: instagram,     user_url: "https://www.instagram.com/jekyll" }
 - { platform: linkedin,      user_url: "https://www.linkedin.com/in/jekyll" }
 - { platform: stackoverflow, user_url: "https://stackoverflow.com/users/1234567/jekyll" }
 - { platform: twitter,       user_url: "https://twitter.com/jekyllrb" }
 - { platform: youtube,       user_url: "https://www.youtube.com/jekyll" }

# Build settings

# SCSS config
sass:
  sass_dir: _sass
  style: nested # possible values: nested expanded compact compressed
